### PR TITLE
Adds support for parsing CARS Psalms and Genesis books

### PR DESCRIPTION
**Pull request by sakhmedbayev**
With these changes, the parser managed to pars CARS translation's book of Psalms.

### CODE REVIEW

**Comment by sakhmedbayev** [comment]
> We view paragraph markers as elements that provide a parallel structure to the Book-Chapter-Verse structure of the usfm files. So they are not supposed to take text content exclusively for themselves. What ever text comes in a paragraph marker should be part of some other element.
> 
> \d is a descriptive section header which has its own content text. And \li is a list marker. We cannot simply consider them as paragraph markers. It may work for some particular files but cannot be considered a general solution. In this case what is applicable for \li should be applicable for other list markers too like \li1, \li2, \lh, etc.... And what applys to \d should apply to \s#, \r etc.
> 
> About \cl, as it is chapter label, it was designed to take only plain text, we had not anticipated it to contain nested footnotes and paragraph markers within them. We shall look into the possibility of allowing nested contents within \cl. But if we do that we should be considering all possible elements and not just notes.
> 
> about \q1 taking text, as I said before, that is not the logic we follow. This text should ideally be part of some other marker(in this case probably \cl). Also we cannot simply define a rule for just q1, it should cover all paragraph markers like \q2, \q3, \p , \b etc
> 
> About +xt, we have not encountered such a usage either in USFM spec nor in any other files we have seen. But we shall consider if it can be accomodated.

Hi @kavitharaju. Thanks for the comments! I understand them, however, I have no control over USFM files that come my way. They are what they are. I think it would be the case whenever human factor is involved. My question is, can we just accommodate for any scenario that comes our way while working on this "usfm-grammar"???

> About accessing the usfm.ohm file directly, we had avoided the use of fs module, in the files part of npm library

may I ask you why this is the issue?

**Comment by kavitharaju** [comment]
Yes. There is a way to accommodate a lot of special cases like these. Work is in progress for a **relaxed** level of strictness in rules. It will be available in our next release which is due early next month(June, 2020).

On your other question, when we use fs, the library is being restricted only to node. We cannot use it from outside node. We want usfm-grammar to be used from a browser/ front-end code also.

**Comment by sakhmedbayev** [comment]
@kavitharaju

>On your other question, when we use fs, the library is being restricted only to node. We cannot use it from outside node. We want usfm-grammar to be used from a browser/ front-end code also.

we can always use the `window` object to determine if the parser is being used in the browser and if it is so then using the *.ohm.js

**Comment by joelthe1** [comment]
Please refer https://github.com/Bridgeconn/usfm-grammar/issues/65#issuecomment-642834765

**Pull request closed without merging**
